name: Arduino Build Check

on: [push, pull_request]

jobs:
  compile-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:m5stack_stamp_s3
          libraries: |
            - name: M5Unified
